<?php

/**
* PwHandsontable Module v 0.9
* Integration of JQuery Plugin "Handsontable" in ProcessWire
*
* @author Stefan Wanzenried (Wanze)
* <http://www.everchanging.ch>
*
* ProcessWire 2.x
* Copyright (C) 2011 by Ryan Cramer
* Licensed under GNU/GPL v2, see LICENSE.TXT
*
* http://www.processwire.com
*
*/
class PwHandsontable extends WireData implements Module {

	const modeView = 1; // Display data as readOnly eventually, optional with actions column
	const modeEdit = 2; // Fields not readOnly are editable in the table
	const modeNew  = 3; // Empty table - insert data to create new Pages. First row = name of fields

	static $instance = 0;

	/**
	 * Default module config options
	 */
	protected static $defaultConfig = array(
		// Default columns to display in the table if no columns or template has been specified
		'columns' => array('id', 'title', 'name', 'path', 'template'),
		// Setting colWidths seems necessary when using custom renderers (currently image/file)
		// Add width in px for each column, e.g. array(40,100,200...)
		'colWidths' => array(),
		// Javascript config passed to Handsontable
		'jsConfig' => array('columnSorting' => true, 'manualColumnResize' => true),
		'limit' => 25,
		'parent' => '',
		'template' => '',
		'sort' => '',
		'includeHidden' => '',
		'includeAll' => '',
		'selector' => '',
		'dateFormat' => 'Y-m-d',
		// Display a filter for searching values in table
		'showFilter' => true,
		// Display actions in last column
		'showActions' => true,
		// Actions to display
		'actions' => array('edit'),
		'mode' => self::modeView,
	);


	/**
	 * Supported Fieldtypes for fields that can be used as columns
	 * key = Fieldtype, renderer = Renderer in Handsontable, readOnly = true if field is not editable in table
	 * Note that Fieldtypes not defined here are not supported by the module and will be skipped
	 */
	protected static $supportedFieldtypes = array(
		'FieldtypePageTitle' => array('renderer' => 'text'),
		'FieldtypeText' => array('renderer' => 'text'),
		'FieldtypeTextarea' => array('renderer' => 'text'),
		'FieldtypeInteger' => array('renderer' => 'numeric'),
		'FieldtypeEmail' => array('renderer' => 'text'),
		'FieldtypeDatetime' => array('renderer' => 'date'),
		'FieldtypeURL' => array('renderer' => 'text'),
		'FieldtypeFloat' => array('renderer' => 'numeric'),
		'FieldtypeCheckbox' => array('renderer' => 'checkbox'),
		//'FieldtypePage' => array('renderer' => 'autocomplete'),
		'FieldtypePage' => array('renderer' => 'text', 'readOnly' => true),
		'FieldtypeFile' => array('renderer' => 'file', 'readOnly' => true),
		'FieldtypeImage' => array('renderer' => 'image', 'readOnly' => true),
	);

	/**
	 * Supported native fields to display in table
	 * Those fields are separated because we can't get them with wire('fields')->get()
	 */
	protected static $nativeFields = array(
		'id' => array('renderer' => 'numeric', 'readOnly' => true),
		'name' => array('renderer' => 'text'),
		'path' => array('renderer' => 'text', 'readOnly' => true),
		'template' => array('renderer' => 'text'),
		'parent' => array('renderer' => 'text'),
		'unpublished' => array('renderer' => 'checkbox'),
		'hidden' => array('renderer' => 'checkbox'),
		'published' => array('renderer' => 'checkbox'),
		'visible' => array('renderer' => 'checkbox'),
		'created' => array('renderer' => 'text', 'readOnly' => true),
		'modified' => array('renderer' => 'text', 'readOnly' => true),
		'actions' => array('renderer' => 'html', 'readOnly' => true),
	);


	public function __construct() {

		// Use WireDatas set()/get() for the module config
		$this->data = self::$defaultConfig;
		self::$instance++;
		$this->setTrackChanges(true);

	}


	/**
	 * Tell ProcessWire something about this module
	 */
	public static function getModuleInfo() {

		return array(
			'title' => 'ProcessWire Handsontable',
			'summary' => 'CRUD functionality for ProcessWire pages/data with the Handsontable Jquery plugin',
			'version' => 100,
			'permanent' => false,
		);

	}


	/**
	 * Load Javascript and CSS
	 */
	public function init() {

		$this->config->scripts->append($this->config->urls->PwHandsontable . 'handsontable/dist/jquery.handsontable.full.js');
		$this->config->scripts->append($this->config->urls->PwHandsontable . 'PwHandsontable.js');
		$this->config->styles->append($this->config->urls->PwHandsontable . 'handsontable/dist/jquery.handsontable.full.css');
		$this->config->styles->append($this->config->urls->PwHandsontable . 'PwHandsontable.css');
		$this->modules->get('JqueryFancybox');

	}


	/**
	 * Remove fields not supported when setting the columns
	 */
	public function set($key, $value) {

		if ($key == 'columns') {
			if (!is_array($value)) throw new WireException('You must set the columns as array');
			foreach ($value as $i => $field) {
				if (!$this->isSupportedField($field)) unset($value[$i]);
			}
		}

		if ($key == 'jsConfig') {
			if (!is_array($value)) throw new WireException('jsConfig must be an array');
			$value = array_merge($this->jsConfig, $value);
		}

		return parent::set($key, $value);

	}


	/**
	 * Renders the table by setting up the required javascript of Handsontable
	 * @return Javascript + HTML Markup
	 */
	public function render() {

		$out = '';
		if ($this->showFilter) {
			$out .= "<div class='pwhot_meta'>";
			$out .= $this->_('Filter') . " <input type='text' class='pwhot_filter'>";
			$out .= "</div>";
		}
		$id = 'pwhot_' . self::$instance;
		$out .= "<div id='{$id}' class='pwhot_table'></div>";
		$out .= "<script>";
		$config = $this->buildJsConfig();
		$out .= "$('#{$id}').handsontable(" . $config . ");";
		$out .= "</script>";
		return $out;

	}

	/**
	 * Build the Javascript config options for Handsontable
	 * @return JSON
	 */
	protected function buildJsConfig() {

		$config = array();
		$config['columns'] = $this->getFormattedColumns();
		$config['data'] = $this->getFormattedData();

		// Use field label for column headers
		$colHeaders = array();
		foreach ($this->columns as $col) {
			$field = $this->fields->get($col);
			$colHeaders[] = (!is_null($field) && $field->label) ? $field->label : $col;
		}
		$config['colHeaders'] = $colHeaders;

		if (count($this->colWidths)) $config['colWidths'] = $this->colWidths;

		// Append custom handsontable configs
		foreach ($this->jsConfig as $k => $v) $config[$k] = $v;

		//echo '<pre>' . json_encode($config) . '</pre>';
		return wireEncodeJSON($config);

	}

	/**
	 * Returns the columns to display in the table with the correct renderer/options for Handsontable
	 * @return array
	 */
	protected function getFormattedColumns() {

		// If we display data from one template, we'll use compatible fields of the template as columns
		// But only if the developer did not specify columns explicitly with ->columns = array('col1', 'col2')
		// TODO: If there's a selector specified with a template, should we extract the template and set it to $this->template?
		$columns = $this->columns;
		if ($this->template && !$this->isChanged('columns')) {
			$columns = array();
			$fields = $this->templates->get($this->template)->fields;
			foreach ($fields as $field) {
				if ($this->isSupportedField($field) && !in_array($field, $columns)) {
					$columns[] = (string) $field;
				}
			}
		}

		if ($this->showActions && ($this->mode == self::modeView || $this->mode == self::modeEdit)) {
			$columns[] = 'actions';
		}

		$this->columns = $columns;

		// Setup columns configs
		$out = array();
		foreach ($columns as $i => $col) {
			$renderer = $this->getRenderer($col);
			$colConfig = array('data' => $col, 'type' => $renderer);
			if ($this->mode == self::modeView || $this->isReadonlyField($col)) $colConfig['readOnly'] = true;
			$out[] = $colConfig;
		}
		return $out;

	}

	/**
	 * Returns the data for handsontable (rows)
	 * @return array
	 */
	protected function getFormattedData() {

		// Build the selector for searching the pages - exclude admin pages
		$selector = "has_parent!={$this->config->adminRootPageID}";

		if ($this->selector) {
			$selector = $this->selector;
		} else {
			if ($this->template) $selector .= ",template={$this->template}";
			if ($this->parent) $selector .= ",parent={$this->parent}";
			if ($this->sort) $selector .= ",sort={$this->sort}";
			if ($this->includeHidden) $selector .= ",include_hidden";
			if ($this->includeAll) $selector .= ",include_all";
		}

		// Make really sure we limit the amount of pages
		if (strpos($selector, 'limit') === false) $selector .= ",limit={$this->limit}";

		$data = array();
		$pages = $this->pages->find($selector);
		foreach ($pages as $page) {
			if (!$page->viewable()) continue;
			$page->of(true);
			$row = array();
			// First column must be the page id -> this column is set to hidden in handsontable
			// Used to reference a page when sending back data
			$row['id'] = $page->id;
			foreach ($this->columns as $col) {
				$row[$col] = $this->getCellValue($page, $col);
			}

			if ($this->showActions && $this->mode != self::modeNew) {
				$row['actions'] = "<a class='pwhot_fancybox' href='{$this->config->urls->admin}page/edit/?id={$page->id}&modal=1'>edit</a>";
			}

			$data[] = $row;
		}

		return $data;
	}


	/**
	 * Return the handsontable renderer for the given field
	 * @param string $fieldName Name of field
	 * @return string|array based on the renderer
	 */
	protected function getRenderer($fieldName) {

		$renderer = array();
		if ($this->isNativeField($fieldName)) {
			$_renderer = self::$nativeFields[$fieldName]['renderer'];
		} else {
			$field =  $this->fields->get($fieldName);
			$fieldType = (string) $field->type;
			$_renderer = self::$supportedFieldtypes[$fieldType]['renderer'];
			// TODO: Other renderer like autocomplete or custom renderer need more setup here...
		}
		$renderer['renderer'] = $_renderer;
		return $renderer;
	}

	/**
	 * Checks of a given field is setup as readOnly
	 */
	protected function isReadonlyField($fieldName) {

		if ($this->isNativeField($fieldName)) {
			$fieldArray = self::$nativeFields[$fieldName];
			return (isset(self::$nativeFields[$fieldName]['readOnly']));
		} else {
			$type = (string) $this->fields->get($fieldName)->type;
			return (isset(self::$supportedFieldtypes[$type]['readOnly']));
		}
	}


	/**
	 * Checks if a field is supported by this module
	 */
	protected function isSupportedField($fieldName) {

		if ($this->isNativeField($fieldName)) return true;

		$field = $this->fields->get($fieldName);
		if ($field == null) return false;
		$fieldType = (string) $field->type;
		/*
		// Page fields are only supported if they hold a single value
		if ($fieldType == 'FieldtypePage') {
			$inputfield = $field->inputfield;
			$module = $this->modules->get($inputfield);
			return !($module instanceof InputfieldHasArrayValue);
		}
		*/
		return (in_array($fieldType, array_keys(self::$supportedFieldtypes)));

	}

	/**
	 * Get the value to display in a cell
	 * @param Page $page The page to get the value from
	 * @param String $col Field name
	 */
	protected function getCellValue($page, $col) {

		$value = '';
		if ($this->isNativeField($col)) {
			switch ($col) {
			case 'unpublished':
				$value = $page->is(Page::statusUnpublished);
				break;
			case 'hidden':
				$value = $page->is(Page::statusHidden);
				break;
			case 'published':
				$value = !$page->is(Page::statusUnpublished);
				break;
			case 'visible':
				$value = !$page->is(Page::statusHidden);
				break;
			case 'created':
			case 'modified':
				$value = date($this->dateFormat, $page->get($col));
				break;
			default:
				$value = (string) $page->get($col);
			}
		} else {
			$field = $page->get($col);
			if ($field instanceof Page) {
				$value = $field->title;
			} else if ($field instanceof PageArray) {
					foreach ($field as $p) $value .= $p->title . "\n";
				} else if ($field instanceof Pagefile) {
					$value = $field->url;
				} else if ($field instanceof Pagefiles && count($field)) {
					$value = array();
					foreach ($field as $f) $value[] = $f->url;
				} else {
				$value = (string) $field;
			}
		}

		return $value;
	}


	protected function isNativeField($fieldName) {
		return in_array($fieldName, array_keys(self::$nativeFields));
	}


}
